### ISSUE TITLE
[BUG] ABM not working anymore

### ISSUE THREAD

**Issue by dunnerak** [Grantapher/ValheimPlus#12]
- **OS:**Windows 10
- **Valheim Game Version:** latest
- **V+ Mod Version:** latest 0.217.14

**Describe the bug**

When placing a wall for example and press F1 to activate ABM, the wall is invisible and cannot be placed.

**Comment by dongerbase** [comment]
getting this issue as well. thanks for keeping this mod alive though!

**Comment by Kogtrey** [comment]
Bumping this as I have had this issue, but am still able to place. Just can't see the piece while ABM is active. Pressing F3 or placing the piece will allow it to re-appear.

**Comment by Grantapher** [comment]
Possible fix in [`0.9.9.18-alpha01`](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.9.18-alpha01).

I have not used the feature before it was broken, so I don't know if the new state it is in is correct. Let me know.

**Comment by Grantapher** [comment]
similar issue in https://github.com/valheimPlus/ValheimPlus/issues/813

**Comment by dunnerak** [comment]
Hi Grantapher!

 

This Version fixed ABM ! It is working again. Thank you so much !

I always use ABM. Its one of the main reasons i use Valheim Plus.

 
 

Gesendet: Montag, 28. August 2023 um 04:31 Uhr
Von: "Grant Toepfer" ***@***.***>
An: "Grantapher/ValheimPlus" ***@***.***>
Cc: "dunnerak" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Grantapher/ValheimPlus] [BUG] ABM not working anymore (Issue #12)


 

Possible fix in 0.9.9.18-alpha01.

I have not used the feature before it was broken, so I don't know if the new state it is in is correct. Let me know.

**Comment by Grantapher** [comment]
Fixed in [0.9.10.0](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.10.0).
