### ISSUE TITLE
[FEATURE REQUEST] Add blackCores to Pickable section

### ISSUE THREAD

**Issue by kaxlabs** [Grantapher/ValheimPlus#19]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**

**Is your feature request related to a problem? If so, please describe.**
Black cores are annoying to get

**Describe the solution you'd like**
Add blackCores to the Pickable section in the config just like surtlingCores

**Additional context**
N/A

**Comment by Grantapher** [comment]
Released into [0.9.10.1-alpha01](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.10.1-alpha01).

**Comment by VulcanTourist** [comment]
Black cores are pickable in a radius for me at this point with the [Q] hotkey, so I suppose that is a confirmation that this now works?

**Comment by Grantapher** [comment]
Yes this should be working.
