### ISSUE TITLE
[FEATURE REQUEST] Increasing Wisp Torch Radius

### ISSUE THREAD

**Issue by Wightwind** [Grantapher/ValheimPlus#20]
**Please review the feature requests already submitted to ensure that you are not submitting a duplicate**
Didnt see another request for this

**Is your feature request related to a problem? If so, please describe.**
The mist is wildly oppressive in the Mistlands (I know its intentional) Just feel like you miss out on the cool environment because of the mist

**Describe the solution you'd like**
Ability to increase Wisp Torches and similar items mist clearing radius

**Additional context**
No context needed, think the request is self explanatory

**Comment by Grantapher** [comment]
Released into [0.9.10.1-alpha01](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.10.1-alpha01).

**Comment by Grantapher** [comment]
Released into [`0.9.11.0`](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.11.0).
