### ISSUE TITLE
[BUG] Same versions, imcompatible though.

### ISSUE THREAD

**Issue by grappas** [Grantapher/ValheimPlus#25]
- **OS:** Linux Server vs Windows Client
- **Valheim Game Version:**  0.217.14 both
- **V+ Mod Version:** 9.9.17

**Describe the bug**

Only difference between server and client is that client is on Windows and server is on Linux. Linux server vs Linux client works fine.
Both client and server has the same version of mod but cannot connect:

```
[Info   : Unity Log] Sending Valheim Plus version 0.9.9.17 and minimum version 0.9.9.17 to the client.
[Info   : Unity Log] 09/20/2023 18:58:11: Got handshake from client 76561198009526993

[Warning: Unity Log] Disconnect: The client (76561198009526993) doesn't have the correct Valheim Plus version 0.9.9.17
[Info   : Unity Log] 09/20/2023 18:58:19: RPC_Disconnect
```

**To Reproduce**

**Expected behavior**

**Troubleshooting**

**Screenshots**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by Grantapher** [comment]
Closing as there is nothing to go on. Feel free to re-open if you can get those logs.
