### ISSUE TITLE
[Mod Compatibility] Server Characters by Smoothbrain

### ISSUE THREAD

**Issue by NeoDragonXDA** [Grantapher/ValheimPlus#26]
- **OS:** [Windows 10 Client, Debian server]
- **Valheim Game Version:** [Latest]
- **V+ Mod Version:** [0.9.9.17]

[Error  :   BepInEx] Could not load [Server Characters 1.4.9] because it is incompatible with: org.bepinex.plugins.valheim_plus

Steps for the devs to reproduce the behavior:
1. Install Valheim plus
2. Install Server Characters on client and server
3. Profit

Would it be possible to make this work?

Is it because ServerSync is wooven in Valheim Plus ?

**Comment by heberholanda** [comment]
I use them and they work well together. 

To make it work, just rename the ValheimPlus mod. Follow the markings.

![image](https://github.com/Grantapher/ValheimPlus/assets/715547/6b4c4a20-56bc-464c-b227-ff3477f6f6de)
