### ISSUE TITLE
[BUG] Patch 0.217.22 Brokes down Valheim Plus

### ISSUE THREAD

**Issue by Beermaster90** [Grantapher/ValheimPlus#29]
- **OS:** [Windows client, Linux Dedicated]
- **Valheim Game Version:** [0.217.22]
- **V+ Mod Version:** [0.9.9.17]

Patch 0.217.22 Brokes down Valheim Plus. Client side can't be started at all. (this is all over discord)

**To Reproduce**

Steps for the devs to reproduce the behavior:
Start valheim client with 0.217.22 version and V+ 0.9.9.17, it will not start.

**Expected behavior**

Valheim will start.

**Comment by Grantapher** [comment]
Fixed as of [0.9.10.0](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.10.0).
