### ISSUE TITLE
[BUG] 0.217.28 incompatible

### ISSUE THREAD

**Issue by mswietlicki** [Grantapher/ValheimPlus#37]
Hi,

Valheim v0.217.28 is incompatible with release v0.9.10.0

There is at least mscorlib.dll version mismatch but maybe more.

**Comment by mswietlicki** [comment]
Probably just needs BepInExPack_Valheim update

**Comment by mswietlicki** [comment]
Duplicate of https://github.com/Grantapher/ValheimPlus/issues/36

**Comment by fbda** [comment]
shit, with Valheim Update 08.11.23 the Server doesn't start

**Comment by vag699** [comment]
atualização de hoje do patch 0.217.29 servidor não começa da erro e fecha

**Comment by Grantapher** [comment]
Fixed in [`0.9.11.0`](https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.11.0).

**Comment by vag699** [comment]
path 0.217.29 ainda sem funcionar ao tentar abrir o jogo apresenta problema e fecha testado com atualizaçãoes disponiveis e nem uma funciona windows 11 pro bild 23H2
