### ISSUE TITLE
[BUG] V+ Wont start with the 0.217.38 valheim version

### ISSUE THREAD

**Issue by RazeDrake** [Grantapher/ValheimPlus#51]
- **OS:** windows client
- **Valheim Game Version:** 0.217.38
- **V+ Mod Version:** 0.9.12.0

**Describe the bug**

V+ wont start in valheim. i bcom many errors in bepInEx

**To Reproduce**

Start the game

**Expected behavior**

**Troubleshooting**

try to reinstall the mod

**Screenshots**

[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (26.11.2023 16:04:18)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity v2022.3.12.5236448
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 4 plugins to load
[Info   :   BepInEx] Loading [Valheim Plus 0.9.12.0]
[Info   :Valheim Plus] Valheim Plus full version: 0.9.12.0
[Info   :Valheim Plus] Trying to load the configuration file
[Info   :Valheim Plus] Found config file at: 'D:\SteamLibrary\steamapps\common\Valheim\BepInEx\config\valheim_plus.cfg'
[Info   :Valheim Plus] Loading config...
[Info   :Valheim Plus]
[Info   :Valheim Plus] [AdvancedBuildingMode] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [AdvancedEditingMode] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Armor] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Bed] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Beehive] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Brightness] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Building] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Camera] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Chat] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [CraftFromChest] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Deconstruct] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Demister] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Durability] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [EitrRefinery] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Experience] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Fermenter] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [FireSource] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [FirstPerson] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Food] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [FreePlacementRotation] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Furnace] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Game] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [GameClock] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Gathering] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [GridAlignment] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Hotkeys] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Hud] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Inventory] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Items] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Kiln] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [LootDrop] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Map] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [MonsterProjectile] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Pickable] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Player] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [PlayerProjectile] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Server] Section is enabled.
[Info   :Valheim Plus] [Server] Updating serverSyncHotkeys from True to False
[Info   :Valheim Plus] [Server] Done with section.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Shields] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Smelter] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [SpinningWheel] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Stamina] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [StaminaUsage] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [StructuralIntegrity] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Tameable] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Time] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [ValheimPlus] Section is enabled.
[Info   :Valheim Plus] [ValheimPlus] Done with section.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Wagon] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Ward] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Windmill] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [WispSpawner] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] [Workbench] Section is NOT enabled.
[Info   :Valheim Plus]
[Info   :Valheim Plus] Downloading config from: 'https://github.com/Grantapher/ValheimPlus/releases/download/0.9.12.0/valheim_plus.cfg'
[Info   :Valheim Plus] Configuration file loaded succesfully.
[Info   :Valheim Plus] Applying patches.
[Info   :Valheim Plus] Patches successfully applied.
[Info   :Valheim Plus] ValheimPlus [0.9.12.0] is up to date.
[Info   :Valheim Plus] ValheimPlus done loading.
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Server Devcommands 1.65]
[Error  : Unity Log] InvalidProgramException: Invalid IL code in (wrapper dynamic-method) Character:DMD<Character::UpdateDebugFly> (Character,single): IL_0097: call      0x00000021

Stack trace:
System.RuntimeMethodHandle.GetFunctionPointer () (at <834b2ded5dad441e8c7a4287897d63c7>:0)
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetFunctionPointer (System.Reflection.MethodBase method, System.RuntimeMethodHandle handle) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetNativeStart (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.DetourHelper.GetNativeStart (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour._TopApply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour._RefreshChain (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour..ctor (System.Reflection.MethodBase from, System.Reflection.MethodBase to, MonoMod.RuntimeDetour.DetourConfig& config) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?-1102987778(object)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
MonoMod.RuntimeDetour.ILHook.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
ServerDevcommands.ServerDevcommands.Awake () (at <d52b617fa5564167be9741babed22a71>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
Fishlabs.Common.SingletonMonoBehaviour`1:get_Instance()
Fishlabs.PlatformManagerInitializer:OnRuntimeMethodLoad()

[Info   :   BepInEx] Loading [Valheim Player Models 1.0.1]
[Message:Valheim Player Models] Found avatar : onyx drake
[Message:Valheim Player Models] Found avatar : philex
[Message:Valheim Player Models] Found avatar : raze drake
[Message:Valheim Player Models] Found avatar : void drake
[Info   :Valheim Player Models] Plugin ValheimPlayerModels is loaded!
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] 12/16/2023 16:35:45: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] 12/16/2023 16:35:45: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] Privilege Multiplayer is not known on this platform. Privilege therefore is granted without check...
[Warning: Unity Log] Privilege UserGeneratedContent is not known on this platform. Privilege therefore is granted without check...
[Warning: Unity Log] Privilege CrossPlay is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] 12/16/2023 16:35:45: Starting to load scene:start

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 12/16/2023 16:35:52: Using steam_appid.txt

[Info   : Unity Log] 12/16/2023 16:35:52: Using steam APPID:892970

Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198406049405 [API loaded no]
[Info   : Unity Log] 12/16/2023 16:35:52: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 12/16/2023 16:35:52: Steam initialized, persona:Razeicrum

[Info   : Unity Log] 12/16/2023 16:35:52: PlayFab custom ID set to "Steam_76561198406049405"

[Info   : Unity Log] 12/16/2023 16:35:52: Using default prefs

[Info   : Unity Log] 12/16/2023 16:35:52: Valheim version: 0.217.38 (network version 20)

[Info   : Unity Log] Trying to set graphic mode to 'Custom'
[Info   : Unity Log] Graphic mode 'Custom' is not or no longer supported. Fallback to default mode for platform...
[Info   : Unity Log] Graphic mode 'Custom' applied!
[Info   : Unity Log] 12/16/2023 16:35:52: Worldgenerator version setup:2

[Info   : Unity Log] 12/16/2023 16:35:52: Render threading mode:MultiThreaded

[Warning: Unity Log] 12/16/2023 16:35:52: Set button "CamZoomIn" to None!

[Warning: Unity Log] 12/16/2023 16:35:52: Set button "CamZoomOut" to None!

[Warning: Unity Log] 12/16/2023 16:35:52: Set button "CamZoomIn" to None!

[Warning: Unity Log] 12/16/2023 16:35:52: Set button "CamZoomOut" to None!

[Warning: Unity Log] Mouse KeyCodes have been deprecated with the new input system. Returning "Key.None"
[Warning: Unity Log] Mouse KeyCodes have been deprecated with the new input system. Returning "Key.None"
[Warning: Unity Log] Mouse KeyCodes have been deprecated with the new input system. Returning "Key.None"
[Warning: Unity Log] Mouse KeyCodes have been deprecated with the new input system. Returning "Key.None"
[Warning: Unity Log] Mouse KeyCodes have been deprecated with the new input system. Returning "Key.None"
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ServerDevcommands.Settings.get_AutoExecBoot () (at <d52b617fa5564167be9741babed22a71>:0)
ServerDevcommands.FejdStartupAwake.Postfix () (at <d52b617fa5564167be9741babed22a71>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Awake>(FejdStartup)

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #0 - 'localization' language: 'German'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #1 - 'localization_extra' language: 'German'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #2 - 'heightmap_message' language: 'German'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #3 - 'localization_hildir' language: 'German'

[Info   : Unity Log] 12/16/2023 16:35:53: Loaded localization file #4 - 'localization_emotes' language: 'German'

[Warning: Unity Log] 12/16/2023 16:35:53: Missing audio clip in music respawn

[Info   : Unity Log] 12/16/2023 16:35:53: Checking for installed DLCs

[Info   : Unity Log] 12/16/2023 16:35:53: DLC:beta installed:False

[Info   : Unity Log] 12/16/2023 16:35:53: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 12/16/2023 16:35:54: PlayFab logged in as "Steam_76561198406049405"

[Info   : Unity Log] 12/16/2023 16:35:54: PlayFab local entity ID is 2AC99BE1491D0F65

**Additional context**

-ServerDevcommands
-VallheimPlayerModels

**Comment by kylegl** [comment]
works fine for me

**Comment by Grantapher** [comment]
Not a V+ issue. Looks like an issue with Server Devcommands since the error is directly after

```
[Info : BepInEx] Loading [Server Devcommands 1.65]
```
