### ISSUE TITLE
[BUG] UnixClient: valheim.x86_64 missing

### ISSUE THREAD

**Issue by afk-duck** [Grantapher/ValheimPlus#55]
- **OS:** Pop_OS! 22.04 LTS
- **Valheim Game Version:** 0.217.38
- **V+ Mod Version:** 0.9.12.0

**Describe the bug**

I followed the installation instructions for the mod, but the game won't start as soon as I set the start command in steam (normal game without mod works).
Except the BepInEx package which comes with the V+ mod, no other mods are installed.
I installed the mod over a fresh Valheim installation and tried with different Proton versions (experimental, 8)

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Install Valheim on Pop_OS! via Steam
2. Install the V+ mod by Grantapher as described in the installation guide (with chmod and start command)
3. Try to start the game via Steam UI

**Expected behavior**

The game should start with the V+ mod.

**Troubleshooting**

1. I reinstalled Valheim completely and freshly installed the mod
2. I tried different Proton versions: Experimental, 8-25 and 8-4

**Screenshots**
![grafik](https://github.com/Grantapher/ValheimPlus/assets/63466503/cca6f606-079e-4616-a0d2-dca39b75e62e)
You can see here, that in the start_game_bepinex.sh on row 27 the file or folder valheim.x86_64 is used, but in my games folder no such file or folder exists.
Even after reinstallation and also a file scan via Steam no such file or folder was installed.

**Additional context**

The installation guide seems to be copy pasted from the server installation as it always talks about server etc.
Does this need an update? I still gave the chmod access for the start_game_bepinex.sh, not only for the server file.

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

I have no other mods installed.

**Comment by Grantapher** [comment]
Does it work without V+?

Is there any file akin to `"$BASEDIR/valheim.*"`?

**Comment by afk-duck** [comment]
Hi, thanks for looking into it :)

Yes, without the V+ mod, the game works perfectly normal.
As you can see in the Screenshot, I have a valheim.exe in my folder. But as my system is a linux one, I don't know if I can even use it.
Yes, my system is 64bit.

![grafik](https://github.com/Grantapher/ValheimPlus/assets/63466503/ccd412d3-c054-4ca9-baf5-edee9edb088b)

**Comment by Grantapher** [comment]
can you try installing [bepinexpack_valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) only and seeing if that works? I think it is an issue with that and not necessarily V+.

**Comment by afk-duck** [comment]
Sorry for the late response. You are right, the problem is the bepinex mod, not the valheim plus mod. Thank you for your help!
