### ISSUE TITLE
[BUG] Malicious Links in Config File

### ISSUE THREAD

**Issue by GitHowitzer** [Grantapher/ValheimPlus#56]
- OS: Any
- Any
- V+ Mod Version: 0.9.12.0

Config file for valheim plus is filled with malicious links - I guess the original domain for valheim.plus has been compromised. These links need to be removed.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Install valheim plus mod
2. Start Valheim so valheim_plug.cfg file gets created.
3. Go to installation folder to edit the valheim_plus.cfg file under "\Steam\steamapps\common\Valheim\BepInEx\config".
4. Search for any valheim.plus links - all are redirected to malicious/malware sites where it tries to install a malware extension.

**Expected behavior**
No malware in any links.

**Comment by luevano** [comment]
Just noticed this when trying to join the discord again (and then finding out about the v+ reforged)

**Comment by Stan-Stani** [comment]
A pr removing the links would be simple. I can do it if necessary.

**Comment by schrer** [comment]
If anyone picks it up: apart from the config file valheim_plus.cfg, there is also a link to the old site in a least these files:

- CONTRIBUTING.md
- README.bbcode
- website/faq/faq.json

And the about section on the base page of this repository has the link as well, this can only be changed by someone with the right permissions on this repository.

**Comment by Grantapher** [comment]
Updated in above commit. Also removed zap stuff. Will be in next alpha targeting next stable.

**Comment by Grantapher** [comment]
Released.
