### ISSUE TITLE
[BUG] Patch 0.217.46 breaks V+/BepinEx (Unity engine updated to version 2022.3.17f)

### ISSUE THREAD

**Issue by kblaschke** [Grantapher/ValheimPlus#58]
- **OS:** Any
- **Valheim Game Version:** 0.217.46
- **V+ Mod Version:** 0.9.12.0

**Describe the bug**

A new Valheim update was just released to the public/stable channel, including a Unity engine update, which breaks compatibility with V+ and BepinEx.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Update Valheim to 0.217.46
2. V+ breaks

**Expected behavior**

V+ and BepinEx should be released with an updated version supporting the new Unity engine.

**Comment by kostafarmakidis** [comment]
Help! is their a workaround to get everything working? Shame they force updates on steam games now

**Comment by kblaschke** [comment]
Not for the new version until Valheim+ has been updated. I didn't check this today, but Iron Gate has a beta channel "old_stable" or similar on Steam with the previous version, so you can continue using the old, working version until the mods are updated. Just have a look into the beta tab in the game's properties, it should be there.

**Comment by kostafarmakidis** [comment]
Ooo almost worked, client went back down to 217.38 but still says incompatible version

**Comment by kostafarmakidis** [comment]
Okay so managed to get it working by: 
- Restarting Valheim server on G-Portal
- Reverted Valheim back to latest version 
- Disabled following in server config: "serverSyncsConfigChanges"

**Comment by Grantapher** [comment]
Coming in here a bit late, but everything should have been already working fine. Unity upgrade shouldn't have an effect.

**Comment by kblaschke** [comment]
Somehow it didn't work right after the update release, causing a crash in BepInEx. After switching to the default_old beta and now back to stable fixed it, while validating the files didn't work when I've reported the issue. Weird, but considering Ashlands is on the doorstep, this will be a non-issue in any case soon, so I'll just close the ticket.

Anyone else still having that problem, trying doing that same beta switch, as this worked for me.
