### ISSUE TITLE
[BUG] Items disappearing using autoFuel and autoDeposit options

### ISSUE THREAD

**Issue by karphead** [Grantapher/ValheimPlus#60]
OS: Win11
Valheim Version: 0.218.12
V+ Mod:  0.9.13.0-alpha01 - Ashlands

I'm experiencing material loss when using the autoFuel and autoDeposit options for the Kiln, Smelter and FireSource. When I place items into a chest they are disappearing. I haven't gotten far enough into the game but I suspect there may be issues with the other crafts as well.

*Steps for the devs to reproduce the behavior*
1. Create a Kiln, Smelter or Fire source
2. Create a crate
3. Add wood, coal, ore, etc to see if they items disappear.

**Troubleshooting**
I did a clean install of Valheim and made sure the beta options were on for Ashlands. I then copied over the 0.913.0 alpha files from the Windows Client zip.

**Link to configuration if applicable:**
[valheim_plus.txt](https://github.com/Grantapher/ValheimPlus/files/15141999/valheim_plus.txt)

**Additional context**
No other mods installed. I attached my current config file.

**Comment by Grantapher** [comment]
Consistently or inconsistently?

**Comment by Grantapher** [comment]
This was fixed in the alpha version you're using so please double check your mod version.

**Comment by karphead** [comment]
It's been consistent and I'm using the alpha version. I've done 2 installs with it and experienced item loss. I'll try another install today just to be sure.

**Comment by Grantapher** [comment]
If you can reproduce it, please give detailed instructions on how to do so. If you can share a log file that would help as well.

**Comment by TheVeon** [comment]
Can confirm this is happening to me and my friend as well (dedicated server), steps to reproduce are simple, build a campfire, place a chest next to it and place wood inside it, we had the campfire swallow 150 wood while staying at 1/10 fuel.

**Comment by Grantapher** [comment]
@TheVeon get the latest 09.13 alpha release from https://github.com/Grantapher/ValheimPlus/releases

**Comment by karphead** [comment]
I've been using alpha02 and played about a week ingame with no issues. I'm guessing I grabbed an older version before.

**Comment by thettenhausen** [comment]
Came here looking to see if it was a know issue maybe, and the alpha fixed it for me on a dedicated server.

**Comment by Grantapher** [comment]
Fixed in 0.9.13.0 release, use latest release.
