### ISSUE TITLE
[ISSUE] Autofuel is not working

### ISSUE THREAD

**Issue by smietanka** [Grantapher/ValheimPlus#64]
Hello, I have started to see after last ashland upgrade that auto fuel (for each resource) is not working.

After upgrade Valheim plus to the newest version, it started to look for me as the torches and fire places are blinking (like trying to fuel manually) every 1-2 seconds but nothing happen. It is quite annoying after some time so I needed to turn off all AutoFuel properties in config.

Please check this issue

**Comment by snorkyware** [comment]
Can confirm.

Pull request submitted: https://github.com/Grantapher/ValheimPlus/pull/65

**Comment by snorkyware** [comment]
PR merged, this can be closed.
