### ISSUE TITLE
[BUG] No longer works with Valheim 0.218.21

### ISSUE THREAD

**Issue by jaevans** [Grantapher/ValheimPlus#96]
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server]
Linux Client
- **Valheim Game Version:** [e.g. 0.4.11, etc]
0.218.21
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]
0.9.13.3

**Describe the bug**

When starting game, player seems to spin rapidly and no controls work. This happens with V+ saves and older non V+ maps and characters.

Looking at the player.log shows a repeated series of 

```
[Error  : Unity Log] MissingFieldException: Field not found: bool .Player.m_firstSpawn Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::OnSpawned>(Player,bool)
Game.SpawnPlayer (UnityEngine.Vector3 spawnPoint, System.Boolean spawnValkyrie) (at <7184024c9322425e8b0d898f0eb8c3fb>:0)
(wrapper dynamic-method) Game.DMD<Game::UpdateRespawn>(Game,single)
Game.FixedUpdate () (at <7184024c9322425e8b0d898f0eb8c3fb>:0)
```

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Start 0.218.21 with V+ enabled
2. Start game

**Expected behavior**

Game works normally

**Troubleshooting**

Disabling V+ makes base game work correctly.

**Screenshots**

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

`m_FirstSpawn` is set in
- [PlayerProfile.cs](https://github.com/Grantapher/ValheimPlus/blob/a980a96712ff60b0c13905a5eb46196402d15b06/ValheimPlus/GameClasses/PlayerProfile.cs#L17`)
- [Game.cs](https://github.com/Grantapher/ValheimPlus/blob/a980a96712ff60b0c13905a5eb46196402d15b06/ValheimPlus/GameClasses/Game.cs#L74)

It also appears in `valheim_Data/Managed/assembly_valheim.dll` so I don't think it was completely removed, but I have no C# or unity experience so I'm not sure how to dig deeper

**Comment by SavidDu** [comment]
I can confirm the same happens on the Windows client as well.

**Comment by jaevans** [comment]
Also verified on Mac version as well. Same versions of Valheim and V+

**Comment by Grantapher** [comment]
https://github.com/Grantapher/ValheimPlus/releases/tag/0.9.14.0-alpha04 this version should work (even though this isn't ptb any more), a new release will be added later.

**Comment by jaevans** [comment]
0.9.14.0 fixes the issues. Closing.
